apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-monitoring-app
  namespace: ai-monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ai-monitoring-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
