apiVersion: v1
kind: Service
metadata:
  name: ai-monitoring-app
  namespace: ai-monitoring
  labels:
    app: ai-monitoring-app
spec:
  selector:
    app: ai-monitoring-app
  ports:
    - port: 8080
      targetPort: 8080
